#-----------------------------------------------------------------------------------------------------------------------
# Help
#-----------------------------------------------------------------------------------------------------------------------

ifeq "$(call lp.help.is-enabled)" "true"

$(call lp.fn.declare-phony-targets, help, lp.target.help)

lp.target.help :
	$(info )
	$(call lp.help.print-targets)

endif

#-----------------------------------------------------------------------------------------------------------------------
# Diagnostics
#-----------------------------------------------------------------------------------------------------------------------

ifeq "$(call lp.diagnostics.is-enabled)" "true"

$(call lp.fn.declare-phony-targets, diagnostics, lp.target.diagnostics)

lp.target.diagnostics : ;
	        $(call lp.fn.print-diagnostics-for-target, Compile, tsc)
	$(info )$(call lp.fn.print-diagnostics-for-target, Bundle, bundle)
	$(info )$(call lp.fn.print-diagnostics-for-target, Clean, clean)

endif

#-----------------------------------------------------------------------------------------------------------------------
# Compile
#-----------------------------------------------------------------------------------------------------------------------

ifeq "$(call lp.tsc.is-enabled)" "true"

$(call lp.fn.declare-phony-targets, tsc, $(call lp.tsc.get-targets))

$(call lp.tsc.get-targets) : $(call lp.tsc.get-prerequisites)
	$(call lp.fn.get-command, Compiling..., tsc)

endif

#-----------------------------------------------------------------------------------------------------------------------
# Bundle
#-----------------------------------------------------------------------------------------------------------------------

ifeq "$(call lp.bundle.is-enabled)" "true"

ifneq "$(call lp.bundle.get-targets)" ""

$(call lp.fn.declare-phony-targets, bundle, $(call lp.bundle.get-targets))

$(call lp.bundle.get-targets) : $(call lp.bundle.get-prerequisites)
	$(call lp.fn.get-command, Bundling..., bundle)

else

$(call lp.fn.declare-phony-targets, bundle, lp.target.bundle)

lp.target.bundle : $(call lp.bundle.get-prerequisites)
    ifeq "$(call lp.bundle.get-command)" "$(call lp.bundle.get-default-command)"
		$(error No bundles have been defined. Call lp.bundle.add-bundle first)
    else
		$(call lp.fn.get-command, Bundling..., bundle)
    endif
endif

endif

#-----------------------------------------------------------------------------------------------------------------------
# Clean
#-----------------------------------------------------------------------------------------------------------------------

ifeq "$(call lp.clean.is-enabled)" "true"

clean:
    ifeq "$(call lp.clean.get-default-command)" "$(call lp.clean.get-command)"
		$(if $(wildcard $(call lp.clean.get-files)), $(call lp.clean.get-command))
    else
		$(call lp.clean.get-command)
    endif

endif
