#!/usr/bin/env bash

# shellcheck disable=SC2046
pnpm install \
    $(npm list -p | grep 'node_modules[/\\]' | sed 's|\r||g;s|\\|/|g;s|.*node_modules/||;s|^|"|;s|$|@latest"|' | grep -v "@types/node") \
    @types/node@$(node --version | sed 's|^v||;s|\..*||')
